baseURL = ""
languageCode = "en-us"
title = "Tushar Chandra"
theme = "windy"
defaultContentLanguage = "en"
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
paginate = 8
enableEmoji = true
uglyurls = true
publishDir = "site"

[permalinks]
posts = "/:sections/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputFormats]

  [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[outputs]
home = [
  "HTML",
  "RSS",
  "SearchIndex"
]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about"
  weight = 2.0

  [[menu.main]]
  identifier = "resume"
  name = "Resume"
  title = "Resume"
  url = "/resume"
  weight = 3.0

  [[menu.main]]
  identifier = "reading"
  name = "Reading"
  title = "Reading"
  url = "/reading"
  weight = 4.0

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  title = "Categories"
  url = "/categories.html"
  weight = 5.0

  [[menu.main]]
  identifier = "archives"
  name = "Archives"
  title = "Archives"
  url = "/posts.html"
  weight = 6.0


[params]
since = 2019.0
dateFormatToUse = "2006-01-02"
mainSections = [
  "posts"
]
enableMathJax = true
sidebar = "right"
widgets = [
  "category",
  "recent_posts"
]

  [params.highlightjs]
  langs = [
    "python",
  ]

  [params.menuIcons]
  enable = true
  home = "fa-home-fill"
  archives = "fa-archive"
  categories = "fa-folder-open"
  tags = "fa-tags"
  about = "fa-mug-hot"
  resume = "fa-file"
  reading = "fa-book-open"

  [params.profile]
  author = "Tushar Chandra"
  author_title = "Data Scientist"
  location = "Chicago, IL"
  follow = "https://github.com/tuchandra"

    [params.profile.social]
    link_tooltip = true

      [params.profile.social.brands]
      # these must be the names of fontawesome icons
      github = "https://github.com/tuchandra"
      linkedin = "https://www.linkedin.com/in/tushar-chandra-76a623b6/"
     
      [params.profile.social.others]
      # these too
      rss = "/index.xml"
      envelope = "mailto:me@tusharc.dev"

  [params.site]
  title = "Hugo"
  favicon = "favicon.ico"

    [params.site.logo]
    enabled = true
    width = 40.0
    height = 40.0
    url = "favicon.ico"

  [params.share]
  enable = false

  [params.config]
  excerpt_link = "Read more"
  toc = true

  [params.search]
  enable = false

[markup.goldmark.renderer]
unsafe = true

