archives:
  other: Archives
menu_Home:
  other: Home
menu_Archives:
  other: Archives
menu_Categories:
  other: Categories
menu_Tags:
  other: Tags
menu_Repository:
  other: Repository
menu_Books:
  other: Books
menu_Movies:
  other: Movies
menu_Links:
  other: Links
menu_About:
  other: About


nav_all:
  other: All
nav_older:
  other: Older
nav_newer:
  other: Newer


page_home:
  other: Home
page_archive:
  other: Archive
page_archives:
  other: Archives
page_category:
  other: Category
page_categories:
  other: Categories
page_tag:
  other: Tag
page_tags:
  other: Tags
page_tagcloud:
  other: Tag Cloud
page_uncategorized:
  other: Uncategorized
page_repository:
  other: Repository
page_douban:
  other: Douban
page_books:
  other: Books
page_books-desc:
  other: Personal collection of books recommended to everyone
page_movies:
  other: Movies
page_movies-desc:
  other: Personal favorite movies recommended to everyone
page_links:
  other: Links
page_links-desc:
  other: Welcome to the exchange link, you can leave a message on this page
page_about:
  other: About

pagination_next:
  other: Next
pagination_prev:
  other: Prev
pagination_page:
  other: Page %d
pagination_pageof:
  other: Page %d of %s

widget_search:
  other: Search
widget_board:
  other: Board
widget_archive:
  other: Archive
widget_tags:
  other: Tags
widget_categories:
  other: Categories
widget_tagcloud:
  other: Tag Cloud
widget_recent_posts:
  other: Recent Posts


profile_follow:
  other: Follow
profile_skill:
  other: Skills
profile_label:
  other: Labels
profile_work:
  other: Works
profile_project:
  other: Projects
profile_link:
  other: Links

insight_hint:
  other: Type something...
insight_posts:
  other: Posts
insight_pages:
  other: Pages
insight_categories:
  other: Categories
insight_tags:
  other: Tags
insight_untitled:
  other: (Untitled)


unit_word:
  other: words
unit_time:
  other: minutes

article_wordcount:
  other: Word Count
article_readcount:
  other: Read Count
article_more:
  other: Read More
article_comments:
  other: Comments
article_share:
  other: Share
article_catalogue:
  other: Catalogue

total_article:
  other: Total %d articles
total_tag:
  other: Total %d tags
total_category:
  other: Total %d categories
total_link:
  other: Total %d links
total_repository:
  other: Total %d projects


donate_qrcode_alt:
  other: Scan Qrcode
donate_qrcode_title:
  other: Scan
donate_button:
  other: $
donate_title:
  other: Maybe you could buy me a cup of coffee.
donate_tip:
  other: Scan this qrcode
donate_alipay_action_tip:
  other: Open alipay app scan this qrcode, buy me a coffee!
donate_wechatpay_action_tip:
  other: Open wechat app scan this qrcode, buy me a coffee!
donate_alipay:
  other: alipay
donate_wechatpay:
  other: wechat payment


comment:
  other: Comment
tweets:
  other: Tweets
share:
  other: Share
rss_feed:
  other: RSS Feed


copyright_theme_by:
  other: Theme by
copyright_base_on:
  other: base on
copyright_powered_by:
  other: Powered by